version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    #ports:
    #  - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    build: ./wildwatch
    # миграция, создание суперпользователя и тестовый сервер
    command:  sh -c "python manage.py migrate --noinput && 
                     python manage.py initadmin &&
                     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wildwatch:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - "8005:8000"
    # Файл содержащий переменные для контейнера
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  celery:
    restart: always
    build:
      context: ./wildwatch
    command: celery -A wildwatch worker -B -l info
    volumes:
      - ./wildwatch:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  flower:
    restart: always
    build:
      context: ./wildwatch
    command: celery -A wildwatch flower
    volumes:
      - ./wildwatch:/usr/src/app/
    ports:
      - "5555:5555"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_volume:
  redis_data: