# Generated by Django 4.0.4 on 2022-05-08 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.IntegerField(verbose_name='Артикул')),
                ('parse_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата парсинга')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price_wo_discount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена без скидки')),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена со скидкой')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('seller', models.CharField(max_length=255, verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.IntegerField(verbose_name='Артикул')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'vendor_code')},
            },
        ),
    ]
