# Generated by Django 4.0.4 on 2022-05-09 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='vendor_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Артикул'),
        ),
    ]
